baseURL = "https://debouilles.github.io/labveiltech2023/"
title = "Déborah Antonietti"

theme = "hugo-theme-puppet-master"


copyright = ""
paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]



[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50



[params]
author = "Déborah Antonietti"
description = "Articles LabVeilTech2023"
keywords = "blog,developer,personal"
img_home = "img/home.jpg"
img_404 = "img/404-bg.jpg"

